import * as vscode from 'vscode';
import * as path from 'path';
import { SiteGenerator } from './SiteGenerator';

export class GeneratorPanel {
    public static currentPanel: GeneratorPanel | undefined;
    private readonly _panel: vscode.WebviewPanel;
    private readonly _extensionUri: vscode.Uri;
    private _disposables: vscode.Disposable[] = [];

    private constructor(panel: vscode.WebviewPanel, extensionUri: vscode.Uri) {
        this._panel = panel;
        this._extensionUri = extensionUri;

        this._panel.onDidDispose(() => this.dispose(), null, this._disposables);

        this._panel.webview.html = this._getWebviewContent();

        this._setWebviewMessageListener(this._panel.webview);
        
        this.updateFileList();
    }

    public static createOrShow(extensionUri: vscode.Uri) {
        const column = vscode.window.activeTextEditor
            ? vscode.window.activeTextEditor.viewColumn
            : undefined;

        if (GeneratorPanel.currentPanel) {
            GeneratorPanel.currentPanel._panel.reveal(column);
            return;
        }

        const panel = vscode.window.createWebviewPanel(
            'mdToDeploy',
            'Site Generator',
            column || vscode.ViewColumn.One,
            {
                enableScripts: true,
                localResourceRoots: [vscode.Uri.joinPath(extensionUri, 'media')]
            }
        );

        GeneratorPanel.currentPanel = new GeneratorPanel(panel, extensionUri);
    }

    public dispose() {
        GeneratorPanel.currentPanel = undefined;

        this._panel.dispose();

        while (this._disposables.length) {
            const x = this._disposables.pop();
            if (x) {
                x.dispose();
            }
        }
    }

    private async updateFileList() {
        const files = await vscode.workspace.findFiles('**/*.md', '**/node_modules/**');
        const workspaceFolders = vscode.workspace.workspaceFolders;
        const rootPath = workspaceFolders ? workspaceFolders[0].uri.fsPath : '';

        const fileData = files.map(file => ({
            absolutePath: file.fsPath,
            relativePath: path.relative(rootPath, file.fsPath)
        }));
        
        this._panel.webview.postMessage({ command: 'listFiles', data: fileData });
    }

    private _setWebviewMessageListener(webview: vscode.Webview) {
        webview.onDidReceiveMessage(
            async (message: any) => {
                const command = message.command;
                
                switch (command) {
                    case 'generate':
                        try {
                            // Save configuration
                            const config = vscode.workspace.getConfiguration('mdToDeploy');
                            await config.update('siteTitle', message.siteTitle, vscode.ConfigurationTarget.Global);
                            await config.update('footerText', message.footerText, vscode.ConfigurationTarget.Global);
                            await config.update('accentColor', message.accentColor, vscode.ConfigurationTarget.Global);

                            const generator = new SiteGenerator();
                            await generator.generateSite(message.files, this._extensionUri, {
                                accentColor: message.accentColor,
                                siteTitle: message.siteTitle,
                                footerText: message.footerText
                            });
                        } catch (error) {
                            vscode.window.showErrorMessage(`Error generating site: ${error}`);
                        }
                        return;
                }
            },
            undefined,
            this._disposables
        );
    }

    // Get Workspace Folder Name
    private _getWorkspaceFolderName(): string {
        if (vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 0) {
            return vscode.workspace.workspaceFolders[0].name;
        }
        return vscode.workspace.name || 'Project';
    }
    

    private _getWebviewContent() {
        const config = vscode.workspace.getConfiguration('mdToDeploy');
        // Use the configured title, or fallback to the workspace name
        // We use || to handle empty strings if the user cleared the setting
        const siteTitle = config.get<string>('siteTitle') || `${this._getWorkspaceFolderName()} Documentation`;
        const footerText = config.get<string>('footerText', `Generated by MD to Deploy`);
        const accentColor = config.get<string>('accentColor', `#007acc`);

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site Generator</title>
    <style>
        body { font-family: sans-serif; padding: 20px; color: var(--vscode-foreground); background-color: var(--vscode-editor-background); }
        .layout { display: flex; gap: 20px; max-height: 100vh; height: calc(100vh - 40px); }
        .sidebar { flex: 1; overflow-y: auto; padding-right: 10px; }
        .preview { flex: 1; border-left: 1px solid var(--vscode-panel-border); padding-left: 20px; display: flex; flex-direction: column; }
        
        ul { list-style-type: none; padding: 0; }
        li { margin: 10px 0; }
        button { padding: 10px 20px; background-color: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; cursor: pointer; }
        button:hover { background-color: var(--vscode-button-hoverBackground); }
        .control-group { margin-bottom: 20px; }
        .accent-color-group { display: flex; align-items: center; gap: 10px; }
        #accent-color { 
            appearance: none;
            -moz-appearance: none;
            -webkit-appearance: none;
            background: none;
            border: 0;
            cursor: pointer;
            height: 40px;
            padding: 0;
            width: 60px;
        }
        label { display: block; margin-bottom: 5px; }
        input[type="text"] { width: 100%; padding: 5px; background-color: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); }
        
        details { margin-bottom: 15px; border: 1px solid var(--vscode-panel-border); padding: 10px; border-radius: 4px; }
        summary { cursor: pointer; font-weight: bold; margin-bottom: 10px; }
        
        /* Tree View Styles */
        .tree-view details { border: none; padding: 0; margin: 0; }
        .tree-view summary { font-weight: normal; margin: 0; padding: 2px 0; }
        .tree-view div { padding-left: 15px; border-left: 1px solid var(--vscode-tree-indentGuidesStroke); }
        
        .view-toggle { display: flex; gap: 10px; margin-bottom: 10px; }
        .view-toggle button { padding: 5px 10px; font-size: 0.9em; }
        .view-toggle button.active { background-color: var(--vscode-button-hoverBackground); }

        /* Preview Styles */
        .preview-frame {
            border: 1px solid #3e3e42;
            border-radius: 4px;
            background-color: #1e1e1e;
            color: #d4d4d4;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            font-size: 0.8rem;
        }
        .preview-header {
            background-color: #252526;
            border-bottom: 1px solid #3e3e42;
            padding: 10px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .preview-header h1 { margin: 0; font-size: 1.2em; color: var(--preview-accent); }
        .preview-body { display: flex; flex: 1; }
        .preview-nav { width: 150px; background-color: #252526; border-right: 1px solid #3e3e42; padding: 10px; }
        .preview-nav a { display: block; padding: 5px; color: #d4d4d4; text-decoration: none; border-radius: 3px; }
        .preview-nav a:hover, .preview-nav a.active { background-color: var(--preview-accent); color: var(--preview-accent-text); }
        .preview-main { flex: 1; padding: 20px; }
        .preview-main h1 { color: var(--preview-accent); margin-top: 0; }
        .preview-main a { color: var(--preview-accent); text-decoration: none; }
        .preview-main blockquote { border-left: 3px solid var(--preview-accent); margin: 0; padding-left: 10px; color: #a0a0a0; }
        .preview-footer { background-color: #252526; border-top: 1px solid #3e3e42; padding: 10px; text-align: center; color: #808080; }
    </style>
</head>
<body>
    <div class="layout">
        <div class="sidebar">
            <h1>Site Generator</h1>
            
            <details open>
                <summary>Customization</summary>
                <div class="control-group">
                    <label for="site-title">Site Title:</label>
                    <input type="text" id="site-title" value="${siteTitle}">
                </div>
                <div class="control-group">
                    <label for="footer-text">Footer Text:</label>
                    <input type="text" id="footer-text" value="${footerText}">
                </div>
                <div class="control-group accent-color-group">
                    <label for="accent-color">Accent Color:</label>
                    <input type="color" id="accent-color" value="${accentColor}">
                </div>
            </details>

            <h2>Select Files</h2>
            <div class="view-toggle">
                <button id="view-list" class="active">List View</button>
                <button id="view-tree">Tree View</button>
            </div>
            <div id="file-container">
                <!-- Files will be populated here -->
            </div>
            <button id="generate-btn" style="margin-top: 20px; width: 100%;">Generate Site</button>
        </div>
        
        <div class="preview">
            <h2>Live Preview</h2>
            <div class="preview-frame" id="preview-frame">
                <header class="preview-header">
                    <div style="width: 20px; height: 2px; background: #d4d4d4; display: flex; flex-direction: column; gap: 3px;">
                        <span style="height: 2px; background: #d4d4d4;"></span>
                        <span style="height: 2px; background: #d4d4d4;"></span>
                        <span style="height: 2px; background: #d4d4d4;"></span>
                    </div>
                    <h1 id="preview-title">${siteTitle}</h1>
                </header>
                <div class="preview-body">
                    <nav class="preview-nav">
                        <a href="#" class="active">Home</a>
                        <a href="#">Getting Started</a>
                        <a href="#">API Reference</a>
                    </nav>
                    <main class="preview-main">
                        <h1>Introduction</h1>
                        <p>Welcome to the documentation. This is a preview of how your site will look.</p>
                        <blockquote>
                            This is a blockquote with the accent color.
                        </blockquote>
                        <p>You can <a href="#">click here</a> to learn more.</p>
                    </main>
                </div>
                <footer class="preview-footer" id="preview-footer">
                    Generated by MD to Deploy
                </footer>
            </div>
        </div>
    </div>

    <script>
        const vscode = acquireVsCodeApi();
        const fileContainer = document.getElementById('file-container');
        const generateBtn = document.getElementById('generate-btn');
        const accentColorInput = document.getElementById('accent-color');
        const siteTitleInput = document.getElementById('site-title');
        const footerTextInput = document.getElementById('footer-text');
        const previewFrame = document.getElementById('preview-frame');
        const previewTitle = document.getElementById('preview-title');
        const previewFooter = document.getElementById('preview-footer');
        const viewListBtn = document.getElementById('view-list');
        const viewTreeBtn = document.getElementById('view-tree');

        let currentFiles = [];
        let currentView = 'list'; // 'list' or 'tree'

        // Contrast calculation logic
        function getContrastColor(hexColor) {
            const hex = hexColor.replace('#', '');
            const r = parseInt(hex.length === 3 ? hex[0] + hex[0] : hex.substring(0, 2), 16);
            const g = parseInt(hex.length === 3 ? hex[1] + hex[1] : hex.substring(2, 4), 16);
            const b = parseInt(hex.length === 3 ? hex[2] + hex[2] : hex.substring(4, 6), 16);
            
            const getLuminance = (c) => {
                const sRGB = c / 255;
                return sRGB <= 0.03928 ? sRGB / 12.92 : Math.pow((sRGB + 0.055) / 1.055, 2.4);
            };
            
            const L = 0.2126 * getLuminance(r) + 0.7152 * getLuminance(g) + 0.0722 * getLuminance(b);
            const whiteContrast = (1.0 + 0.05) / (L + 0.05);
            const blackContrast = (L + 0.05) / (0.0 + 0.05);
            
            return whiteContrast > blackContrast ? '#ffffff' : '#000000';
        }

        function updatePreview() {
            const color = accentColorInput.value;
            const contrast = getContrastColor(color);
            previewFrame.style.setProperty('--preview-accent', color);
            previewFrame.style.setProperty('--preview-accent-text', contrast);
            
            previewTitle.textContent = siteTitleInput.value;
            previewFooter.textContent = footerTextInput.value;
        }

        // Initialize preview
        updatePreview();

        // Listen for changes
        accentColorInput.addEventListener('input', updatePreview);
        siteTitleInput.addEventListener('input', updatePreview);
        footerTextInput.addEventListener('input', updatePreview);

        // View Toggles
        viewListBtn.addEventListener('click', () => {
            currentView = 'list';
            viewListBtn.classList.add('active');
            viewTreeBtn.classList.remove('active');
            renderFiles();
        });

        viewTreeBtn.addEventListener('click', () => {
            currentView = 'tree';
            viewTreeBtn.classList.add('active');
            viewListBtn.classList.remove('active');
            renderFiles();
        });

        function buildFileTree(files) {
            const tree = {};
            files.forEach(file => {
                const parts = file.relativePath.replace(/\\\\/g, '/').split('/');
                let currentLevel = tree;
                parts.forEach((part, index) => {
                    const isFile = index === parts.length - 1;
                    if (!currentLevel[part]) {
                        currentLevel[part] = isFile ? { _file: file } : {};
                    }
                    if (!isFile) {
                        currentLevel = currentLevel[part];
                    }
                });
            });
            return tree;
        }

        function generateTreeHTML(tree, fullPath = '') {
            let html = '';
            const keys = Object.keys(tree).sort((a, b) => {
                // Folders first, then files
                const aIsFile = !!tree[a]._file;
                const bIsFile = !!tree[b]._file;
                if (aIsFile === bIsFile) return a.localeCompare(b);
                return aIsFile ? 1 : -1;
            });

            keys.forEach(key => {
                const item = tree[key];
                if (item._file) {
                    // File
                    html += \`
                    <div class="file-item">
                        <label style="display: flex; align-items: center; gap: 5px; cursor: pointer;">
                            <input type="checkbox" class="file-checkbox" value="\${item._file.absolutePath}" checked />
                            <span class="file-name">\${key}</span>
                        </label>
                    </div>\`;
                } else {
                    // Folder
                    html += \`
                    <details open>
                        <summary>
                            <label style="display: inline-flex; align-items: center; gap: 5px; cursor: pointer;" onclick="event.stopPropagation()">
                                <input type="checkbox" class="folder-checkbox" checked />
                                <span>\${key}</span>
                            </label>
                        </summary>
                        <div style="padding-left: 15px; border-left: 1px solid var(--vscode-tree-indentGuidesStroke);">
                            \${generateTreeHTML(item)}
                        </div>
                    </details>\`;
                }
            });
            return html;
        }

        function renderFiles() {
            fileContainer.innerHTML = '';
            
            if (currentView === 'list') {
                const ul = document.createElement('ul');
                currentFiles.forEach(file => {
                    const li = document.createElement('li');
                    const checkbox = document.createElement('input');
                    checkbox.type = 'checkbox';
                    checkbox.className = 'file-checkbox';
                    checkbox.value = file.absolutePath;
                    checkbox.checked = true;
                    
                    const label = document.createElement('label');
                    label.style.display = 'inline';
                    label.textContent = file.relativePath;
                    
                    li.appendChild(checkbox);
                    li.appendChild(document.createTextNode(' '));
                    li.appendChild(label);
                    ul.appendChild(li);
                });
                fileContainer.appendChild(ul);
            } else {
                const tree = buildFileTree(currentFiles);
                const treeHTML = generateTreeHTML(tree);
                const div = document.createElement('div');
                div.className = 'tree-view';
                div.innerHTML = treeHTML;
                fileContainer.appendChild(div);

                // Add event listeners for folder checkboxes
                const folderCheckboxes = div.querySelectorAll('.folder-checkbox');
                folderCheckboxes.forEach(cb => {
                    cb.addEventListener('change', (e) => {
                        const checkbox = e.target;
                        const details = checkbox.closest('details');
                        const childCheckboxes = details.querySelectorAll('input[type="checkbox"]');
                        childCheckboxes.forEach(child => {
                            if (child !== checkbox) {
                                child.checked = checkbox.checked;
                            }
                        });
                    });
                });
            }
        }

        window.addEventListener('message', event => {
            const message = event.data;
            switch (message.command) {
                case 'listFiles':
                    currentFiles = message.data;
                    renderFiles();
                    break;
            }
        });

        generateBtn.addEventListener('click', () => {
            const checkboxes = fileContainer.querySelectorAll('input.file-checkbox:checked');
            const selectedFiles = Array.from(checkboxes).map(cb => cb.value);
            
            vscode.postMessage({
                command: 'generate',
                files: selectedFiles,
                accentColor: accentColorInput.value,
                siteTitle: siteTitleInput.value,
                footerText: footerTextInput.value
            });
        });
    </script>
</body>
</html>`;
    }
}
